sonar.projectKey=powerpulse
sonar.projectName=powerpulse
sonar.projectVersion=1.0

# Where your source code is
sonar.sources=src

# Files that are tests (not counted as source)
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

# Do not analyze these
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.test.jsx,**/*.test.js

# Test coverage report (optional, see below)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
